#:kivy 1.0

<PeopleListView>:
	GridLayout:
		cols: 1
		row_default_height: 40
		ScrollView:
			do_scroll_x: False
			GridLayout:
				cols: 1
				size_hint_y: None
				height: self.minimum_height
				row_default_height: 40
				row_force_default: True
				id: people
		GridLayout:
			cols: 2
			size_hint_y: 0.07
			Button:
				text: 'Add'				
				on_press: root.addButtonClick(self)
			Button:
				text: 'Cancel'				
				on_press: root.cancelButtonClick(self)